### ISSUE TITLE
get more inspiration from Litewrite

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/notes#10]
The ownCloud Notes app already is modeled a lot after [Litewrite](http://litewrite.net) by @jorin-vogel and me. It’s battle tested and we put quite some thought in how to design a good simple notes app. So here are some more points where we can improve the Notes app, taken from issues we solved or we’re planning to solve in Litewrite:
- [x] [word count on bottom of document](https://github.com/litewrite/litewrite/issues/122), simple addition and very useful for writers
- [ ] [document count on bottom of document list](https://github.com/litewrite/litewrite/issues/123), just a faint »34 notes« similar to the »Show only unread« toggle in the News app. The news app could also have »34 sites, show only unread« as toggle label to make it more useful. Might even be good to have the functionality/style core-ish
- [ ] [make some parts unselectable](https://github.com/litewrite/litewrite/issues/85), to intercept the weird look which appears when you select some interface element by mistake (or Ctrl+A) – maybe also useful in to put it in core styles, but we need to make sure that inputs and such still are selectable
- [ ] [shadow scroll indicator](https://github.com/litewrite/litewrite/issues/36), a slight shadow on top and bottom. I still need to test if this causes [scroll issues](https://github.com/litewrite/litewrite/issues/69) though, but otherwise we could also put it in core.
- [ ] [fade when switching documents](https://github.com/litewrite/litewrite/issues/33), just a very very quick and slight fade. Maybe, maybe not?
- [x] [visualize the age of notes](https://github.com/litewrite/litewrite/issues/31), like we already do in the Files app. Notes are sorted by modified date, newest first. Now in addition the opacity of the note title could decrease (until it’s still easily readable), the older it is.
- [ ] [tab character behavior](https://github.com/litewrite/litewrite/issues/26), as pressing tab will throw you out of the textarea, tab should instead force a tab character to be inserted (if possible)
- [ ] [AppCache](https://github.com/litewrite/litewrite/issues/8), this is actually something which all of ownCloud should do to not need to load all assets into the browser every time.
- [ ] [localStorage](https://github.com/litewrite/litewrite/issues/7), similar to AppCache, the notes themselves should be locally cached in localStorage/indexedDB so they don’t need to be loaded from the server every time.
- [ ] [search notes](https://github.com/litewrite/litewrite/issues/91), as already said in https://github.com/owncloud/core/issues/821#issuecomment-15840972, I think it’s best to have no global search, and instead for each app to have their own. cc @butonic 
- [ ] [animation for notes moving up in the list](https://github.com/litewrite/litewrite/issues/57), to better visualize what happens when you edit an oder document, instead of just having it jump to the top
- [ ] [blank slate](https://github.com/litewrite/litewrite/issues/30), when you initially open the app, there should probably be a demo note as an introduction. When you have no notes, the textarea should be focused. When you have notes and open the app, the last edited note should be automatically opened and focused
- [ ] [autosave & restore scroll and cursor position in note](https://github.com/litewrite/litewrite/issues/27), kind of a tough one, but that would be great for long notes, so that you’re not always thrown to the top
- [ ] [show date](https://github.com/litewrite/litewrite/issues/25), see #1 
- [ ] [public sharing & publishing](https://github.com/litewrite/litewrite/issues/19), would be awesome if you can share a note with a public link right from within the app. Also a good demo for the template

cc @Raydiation, also @icewind1991 @caco3
