### ISSUE TITLE
[QA] 2.0.7 Testplan

### ISSUE THREAD

**Issue by jnweiger** [owncloud/notes#489]
## Setup

`bash hetzner-deploy/oc10.sh notes`

## Testing functionality

* [x] Update from notes app 2.0.5
   - [x] User receives shared Notes folder
   - [x] User starts the old notes app, happily adds notes (which is a security issue)
   - [x] Admin updates to the notes app including #488
   - [x] The new notes app changes notesRoot to a 'Notes (2)' folder. Which is now empty.
   - [x] User panics, as he believes all his notes are lost. (Until he realizes the exiatance of the original 'Notes' folder.)
      --> https://github.com/owncloud/notes/pull/488#issuecomment-2364028100

* [x] #488 share an existing Notes folder
   - [x] `echo "insert into oc_preferences values ( 'admin', 'notes', 'notesRoot', 'NotesDir');"  | mysql owncloud`
   - [x] add some notes.
   - [x] share the /NotesDir folder with other user
   - [x] add some more notes. Check for newly created '/NotesDir (2)' folder. None expected.
   - [x] Old notes should be still there. They are.

* [x] #488 configure notesRoot into a subfolder of a share
   - [x] Share folder /Shared with other user.
   - [x] `echo "update oc_preferences set configvalue = '/Shared/NotesSub' where userid='admin' and appid='notes' and configkey='notesRoot'"  | mysql owncloud`
   - [x] Add some notes. Check for newly created toplevel folder 'Notes'.
   - [x] Add some more notes. Are multiple `/Shared/NotesSub (\d)` folders created? No.

----

**Comment by jnweiger** [comment]
QA passed, except for perhaps https://github.com/owncloud/notes/pull/488#issuecomment-2364028100 (which is collateral damage due to added security.)

**Comment by jnweiger** [comment]
jumping to 2.0.7, as marketplace saw a 2.0.6 in 2019 :see_no_evil:
